package com.example.rus_r.model;

public class Flashcard {
    private String id;
    private String subjectId;
    private String front; // Question or term
    private String back; // Answer or definition
    private long createdAt;
    private long updatedAt;
    private boolean isAutoGenerated; // Generated by AI or manually created
    private String relatedLessonId; // ID of lesson used to generate flashcard
    private int reviewCount; // Number of times reviewed
    private boolean isFavorite;

    // Constructor
    public Flashcard() {
    }

    public Flashcard(String id, String subjectId, String front, String back) {
        this.id = id;
        this.subjectId = subjectId;
        this.front = front;
        this.back = back;
        this.createdAt = System.currentTimeMillis();
        this.updatedAt = System.currentTimeMillis();
        this.isAutoGenerated = false;
        this.reviewCount = 0;
        this.isFavorite = false;
    }

    // Getters and Setters
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getSubjectId() {
        return subjectId;
    }

    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }

    public String getFront() {
        return front;
    }

    public void setFront(String front) {
        this.front = front;
    }

    public String getBack() {
        return back;
    }

    public void setBack(String back) {
        this.back = back;
    }

    public long getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(long createdAt) {
        this.createdAt = createdAt;
    }

    public long getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(long updatedAt) {
        this.updatedAt = updatedAt;
    }

    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        isAutoGenerated = autoGenerated;
    }

    public String getRelatedLessonId() {
        return relatedLessonId;
    }

    public void setRelatedLessonId(String relatedLessonId) {
        this.relatedLessonId = relatedLessonId;
    }

    public int getReviewCount() {
        return reviewCount;
    }

    public void setReviewCount(int reviewCount) {
        this.reviewCount = reviewCount;
    }

    public boolean isFavorite() {
        return isFavorite;
    }

    public void setFavorite(boolean favorite) {
        isFavorite = favorite;
    }
}