package com.example.rus_r.model;

import java.util.ArrayList;
import java.util.List;

public class Quiz {
    private String id;
    private String subjectId;
    private String title;
    private String description;
    private String difficulty; // "easy", "medium", "hard"
    private int totalQuestions;
    private long createdAt;
    private long updatedAt;
    private boolean isAutoGenerated; // Generated by AI or manually created
    private String relatedLessonId; // ID of lesson used to generate quiz

    // Constructor
    public Quiz() {
    }

    public Quiz(String id, String subjectId, String title, String difficulty, int totalQuestions) {
        this.id = id;
        this.subjectId = subjectId;
        this.title = title;
        this.difficulty = difficulty;
        this.totalQuestions = totalQuestions;
        this.createdAt = System.currentTimeMillis();
        this.updatedAt = System.currentTimeMillis();
        this.isAutoGenerated = false;
    }

    // Getters and Setters
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getSubjectId() {
        return subjectId;
    }

    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDifficulty() {
        return difficulty;
    }

    public void setDifficulty(String difficulty) {
        this.difficulty = difficulty;
    }

    public int getTotalQuestions() {
        return totalQuestions;
    }

    public void setTotalQuestions(int totalQuestions) {
        this.totalQuestions = totalQuestions;
    }

    public long getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(long createdAt) {
        this.createdAt = createdAt;
    }

    public long getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(long updatedAt) {
        this.updatedAt = updatedAt;
    }

    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        isAutoGenerated = autoGenerated;
    }

    public String getRelatedLessonId() {
        return relatedLessonId;
    }

    public void setRelatedLessonId(String relatedLessonId) {
        this.relatedLessonId = relatedLessonId;
    }
}