package com.example.rus_r.ai;

import android.util.Log;

import androidx.lifecycle.LiveData;
import androidx.lifecycle.MutableLiveData;

import com.example.rus_r.model.Flashcard;
import com.example.rus_r.util.ValidationUtils;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class FlashcardGenerator {
    private static final String TAG = "FlashcardGenerator";

    /**
     * Generate flashcards from lesson content
     */
    public static LiveData<List<Flashcard>> generateFlashcards(String lessonContent, String lessonId, String subjectId) {
        MutableLiveData<List<Flashcard>> result = new MutableLiveData<>();

        if (ValidationUtils.isEmpty(lessonContent)) {
            Log.e(TAG, "Lesson content is empty");
            result.setValue(new ArrayList<>());
            return result;
        }

        try {
            List<Flashcard> flashcards = new ArrayList<>();

            // Extract key concepts from content
            List<String> concepts = extractConcepts(lessonContent);

            // Create flashcard for each concept
            for (String concept : concepts) {
                Flashcard flashcard = createFlashcard(concept, lessonContent, lessonId, subjectId);
                if (flashcard != null) {
                    flashcards.add(flashcard);
                }
            }

            result.setValue(flashcards);
            Log.d(TAG, "Generated " + flashcards.size() + " flashcards");

        } catch (Exception e) {
            Log.e(TAG, "Error generating flashcards: " + e.getMessage());
            result.setValue(new ArrayList<>());
        }

        return result;
    }

    /**
     * Extract key concepts from lesson content
     */
    private static List<String> extractConcepts(String lessonContent) {
        List<String> concepts = new ArrayList<>();

        // Split content into sentences
        String[] sentences = lessonContent.split("[.!?]+");

        // Extract meaningful sentences as concepts
        for (String sentence : sentences) {
            sentence = sentence.trim();
            if (sentence.length() > 20 && sentence.length() < 200) {
                concepts.add(sentence);
                if (concepts.size() >= 10) break; // Limit to 10 concepts
            }
        }

        return concepts;
    }

    /**
     * Create single flashcard
     */
    private static Flashcard createFlashcard(String concept, String lessonContent, String lessonId, String subjectId) {
        try {
            Flashcard flashcard = new Flashcard();
            flashcard.setId(UUID.randomUUID().toString());
            flashcard.setSubjectId(subjectId);
            flashcard.setRelatedLessonId(lessonId);
            flashcard.setAutoGenerated(true);

            // Extract key term as front
            String keyTerm = extractKeyTerm(concept);
            flashcard.setFront(keyTerm);

            // Use concept as definition (back)
            flashcard.setBack(concept.trim());

            return flashcard;

        } catch (Exception e) {
            Log.e(TAG, "Error creating flashcard: " + e.getMessage());
            return null;
        }
    }

    /**
     * Extract key term from concept
     */
    private static String extractKeyTerm(String concept) {
        String[] words = concept.split("\\s+");

        if (words.length == 0) {
            return "Term";
        }

        // Find longest word (usually the key term)
        String keyTerm = words[0];
        for (String word : words) {
            // Remove punctuation
            word = word.replaceAll("[^a-zA-Z0-9]", "");

            if (word.length() > keyTerm.length() && word.length() > 3) {
                keyTerm = word;
            }
        }

        return keyTerm;
    }

    /**
     * Generate definition for key term
     */
    private static String generateDefinition(String keyTerm, String lessonContent) {
        // Find sentences containing the key term
        String[] sentences = lessonContent.split("[.!?]+");

        for (String sentence : sentences) {
            if (sentence.toLowerCase().contains(keyTerm.toLowerCase())) {
                return sentence.trim();
            }
        }

        return "See lesson content for definition";
    }

    /**
     * Batch generate flashcards
     */
    public static LiveData<Integer> generateFlashcardCount(String lessonContent) {
        MutableLiveData<Integer> result = new MutableLiveData<>();

        try {
            List<String> concepts = extractConcepts(lessonContent);
            result.setValue(concepts.size());
        } catch (Exception e) {
            Log.e(TAG, "Error counting flashcards: " + e.getMessage());
            result.setValue(0);
        }

        return result;
    }
}