package com.example.rus_r.ai;

import android.util.Log;

import androidx.lifecycle.LiveData;
import androidx.lifecycle.MutableLiveData;

import com.example.rus_r.model.Question;
import com.example.rus_r.model.Quiz;
import com.example.rus_r.util.Constants;
import com.example.rus_r.util.ValidationUtils;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class QuizGenerator {
    private static final String TAG = "QuizGenerator";

    /**
     * Generate quiz from lesson content
     */
    public static LiveData<Quiz> generateQuiz(String lessonContent, String lessonId, String subjectId, String difficulty) {
        MutableLiveData<Quiz> result = new MutableLiveData<>();

        if (ValidationUtils.isEmpty(lessonContent)) {
            Log.e(TAG, "Lesson content is empty");
            result.setValue(null);
            return result;
        }

        try {
            // Create quiz
            Quiz quiz = new Quiz();
            quiz.setId(UUID.randomUUID().toString());
            quiz.setSubjectId(subjectId);
            quiz.setTitle("Auto-generated Quiz from " + lessonId);
            quiz.setDescription("Quiz auto-generated from lesson content");
            quiz.setDifficulty(difficulty);
            quiz.setAutoGenerated(true);
            quiz.setRelatedLessonId(lessonId);

            // Generate 5-10 questions from content
            int questionCount = getQuestionCount(difficulty);
            quiz.setTotalQuestions(questionCount);

            result.setValue(quiz);
            Log.d(TAG, "Quiz generated successfully");

        } catch (Exception e) {
            Log.e(TAG, "Error generating quiz: " + e.getMessage());
            result.setValue(null);
        }

        return result;
    }

    /**
     * Generate questions from lesson content
     */
    public static LiveData<List<Question>> generateQuestions(String lessonContent, String quizId, String difficulty, int questionCount) {
        MutableLiveData<List<Question>> result = new MutableLiveData<>();

        if (ValidationUtils.isEmpty(lessonContent)) {
            Log.e(TAG, "Lesson content is empty");
            result.setValue(new ArrayList<>());
            return result;
        }

        try {
            List<Question> questions = new ArrayList<>();

            // Extract sentences from content
            String[] sentences = lessonContent.split("[.!?]+");

            // Generate questions from sentences
            int questionNumber = 1;
            for (int i = 0; i < Math.min(questionCount, sentences.length); i++) {
                String sentence = sentences[i].trim();

                if (sentence.length() > 20) { // Only process meaningful sentences
                    Question question = generateSingleQuestion(sentence, quizId, questionNumber, difficulty);
                    if (question != null) {
                        questions.add(question);
                        questionNumber++;
                    }
                }
            }

            result.setValue(questions);
            Log.d(TAG, "Generated " + questions.size() + " questions");

        } catch (Exception e) {
            Log.e(TAG, "Error generating questions: " + e.getMessage());
            result.setValue(new ArrayList<>());
        }

        return result;
    }

    /**
     * Generate single question from sentence
     */
    private static Question generateSingleQuestion(String sentence, String quizId, int questionNumber, String difficulty) {
        try {
            Question question = new Question();
            question.setId(UUID.randomUUID().toString());
            question.setQuizId(quizId);
            question.setQuestionNumber(questionNumber);
            question.setDifficulty(difficulty);

            // Randomly choose question type
            String questionType = chooseQuestionType();
            question.setQuestionType(questionType);

            // Create question text from sentence
            String questionText = convertToQuestion(sentence);
            question.setQuestionText(questionText);

            if (questionType.equals(Constants.QUESTION_TYPE_MULTIPLE_CHOICE)) {
                // Generate multiple choice options
                List<String> options = generateOptions(sentence);
                question.setOptions(options);
                question.setCorrectAnswer(options.get(0)); // First option is correct
            } else {
                // For other types, extract key term as answer
                String answer = extractKeyTerm(sentence);
                question.setCorrectAnswer(answer);
            }

            return question;

        } catch (Exception e) {
            Log.e(TAG, "Error generating single question: " + e.getMessage());
            return null;
        }
    }

    /**
     * Convert sentence to question
     */
    private static String convertToQuestion(String sentence) {
        // Simple conversion: add "What is/are" or "Explain"
        if (sentence.contains("is") || sentence.contains("are")) {
            return "What is the meaning of: " + sentence.trim();
        } else {
            return "Explain: " + sentence.trim();
        }
    }

    /**
     * Generate multiple choice options
     */
    private static List<String> generateOptions(String sentence) {
        List<String> options = new ArrayList<>();

        // Extract key term as correct answer
        String keyTerm = extractKeyTerm(sentence);
        options.add(keyTerm);

        // Add dummy options (in real app, these would be generated smartly)
        options.add("Alternative 1");
        options.add("Alternative 2");
        options.add("Alternative 3");

        return options;
    }

    /**
     * Extract key term from sentence
     */
    private static String extractKeyTerm(String sentence) {
        String[] words = sentence.split("\\s+");
        if (words.length > 0) {
            // Return longest word (usually the key term)
            String keyTerm = words[0];
            for (String word : words) {
                if (word.length() > keyTerm.length()) {
                    keyTerm = word;
                }
            }
            return keyTerm;
        }
        return "Answer";
    }

    /**
     * Choose random question type
     */
    private static String chooseQuestionType() {
        String[] types = {
                Constants.QUESTION_TYPE_MULTIPLE_CHOICE,
                Constants.QUESTION_TYPE_IDENTIFICATION,
                Constants.QUESTION_TYPE_TYPING
        };
        return types[(int) (Math.random() * types.length)];
    }

    /**
     * Get question count based on difficulty
     */
    private static int getQuestionCount(String difficulty) {
        switch (difficulty.toLowerCase()) {
            case Constants.DIFFICULTY_EASY:
                return 5;
            case Constants.DIFFICULTY_MEDIUM:
                return 8;
            case Constants.DIFFICULTY_HARD:
                return 10;
            default:
                return 5;
        }
    }
}